life-manager-app/apps/habit_tracker/urls.py
from django.urls import path

from . import views

app_name = "habit_tracker"
urlpatterns = [
    path("habit-tracker/", views.habit_tracker, name="habit_tracker"),
    path("habit-tracker/<int:week_number>/<int:year>", views.habit_tracker, name="habit_tracker"),
    path("habit-tracker/create-habit/", views.create_habit, name="create_habit"),
    path("habit-tracker/update-recurrence/", views.update_recurrence, name="update_recurrence"),
    path(
        "mark-completed/<int:week>/<int:year>/<str:date>/",
        views.MarkCompletedView.as_view(),
        name="mark_completed",
    ),
]

life-manager-app/life_manager_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.finance.urls", namespace="finance")),
    path("", include("apps.habit_tracker.urls", namespace="habit_tracker")),
]

life-manager-app/apps/habit_tracker/models.py
from datetime import datetime, timedelta

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Week(models.Model):
    year = models.PositiveIntegerField()
    week_number = models.PositiveIntegerField()

    class Meta:
        unique_together = (
            "year",
            "week_number",
        )

    def __str__(self):
        return f"Week {self.week_number}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        existing_days = self.day_set.all()

        if not existing_days:
            jan4 = datetime(self.year, 1, 4)
            start_of_year_week = jan4 - timedelta(days=jan4.isoweekday() - 1)
            week_start = start_of_year_week + timedelta(weeks=self.week_number - 1)
            start_date = week_start - timedelta(days=(week_start.weekday() + 1) % 7)

            for i in range(7):
                date = start_date + timezone.timedelta(days=i)
                Day.objects.get_or_create(date=date, week=self)


class Day(models.Model):
    date = models.DateField(unique=True)
    week = models.ForeignKey(Week, on_delete=models.CASCADE)
    habits = models.ManyToManyField("Habit", through="HabitSchedule", related_name="scheduled_habits")

    def __str__(self):
        return f"{self.date} - Week {self.week.week_number}"


class Habit(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    goal = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.name


class HabitRecurrence(models.Model):
    habit = models.ForeignKey(Habit, on_delete=models.CASCADE)
    days_of_week = models.ManyToManyField("DayOfWeekChoice", related_name="habit_recurrences")
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.habit.name} recurrence on {', '.join(day.get_day_of_week_display() for day in self.days_of_week.all())}"


class DayOfWeekChoice(models.Model):
    day_of_week = models.CharField(
        max_length=10,
        choices=[
            ("Sunday", "Sunday"),
            ("Monday", "Monday"),
            ("Tuesday", "Tuesday"),
            ("Wednesday", "Wednesday"),
            ("Thursday", "Thursday"),
            ("Friday", "Friday"),
            ("Saturday", "Saturday"),
        ],
        unique=True,
    )

    def __str__(self):
        return self.get_day_of_week_display()


class HabitSchedule(models.Model):
    habit = models.ForeignKey(Habit, on_delete=models.CASCADE)
    day = models.ForeignKey(Day, on_delete=models.CASCADE)

    SUCCESS = "success"
    FAILED = "failed"
    NOT_COMPLETED = "not_completed"

    COMPLETION_CHOICES = [
        (SUCCESS, "Success"),
        (FAILED, "Failed"),
        (NOT_COMPLETED, "Not Completed"),
    ]

    completion_status = models.CharField(
        max_length=15,
        choices=COMPLETION_CHOICES,
        default=NOT_COMPLETED,
    )

    description = models.TextField(blank=True, null=True)
    time_spent = models.DurationField(blank=True, null=True, default=timedelta(minutes=0))

    class Meta:
        unique_together = (
            "habit",
            "day",
        )

    def __str__(self):
        return f"{self.habit.name} scheduled for {self.day.date}"

life-manager-app/apps/habit_tracker/views.py
from datetime import datetime, timedelta

from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils import timezone
from django.views import View

from .models import DayOfWeekChoice, Habit, HabitRecurrence, HabitSchedule, Week
from .utils.view_utils import calculate_weeks_and_years, create_schedules, format_date


@login_required
def habit_tracker(request, week_number=None, year=None):
    if week_number is None or year is None:
        today = datetime.now().date()
        start_of_week = today - timedelta(days=today.weekday())
        week_number = start_of_week.isocalendar()[1]
        year = today.year

    current_week, _ = Week.objects.get_or_create(week_number=week_number, year=year)

    week_days = current_week.day_set.all()

    for day in week_days:
        format_date(day)

        # Pega todas as recorrências que possivelmente possuem essa data
        active_recurrences = HabitRecurrence.objects.filter(
            Q(end_date__gte=day.date) | Q(end_date__isnull=True),
            start_date__lte=day.date,
        )

        if active_recurrences:
            # Loop through each active recurrence
            for recurrence in active_recurrences:
                # Determine the days of the week for which the habit should be scheduled
                days_to_schedule = recurrence.days_of_week.filter(day_of_week=day.date.strftime("%A"))

                # Check if there are days to schedule
                if days_to_schedule.exists():
                    HabitSchedule.objects.get_or_create(habit=recurrence.habit, day=day)

        day.habit_schedules = HabitSchedule.objects.filter(day=day).order_by("habit__name")

        for habit_schedule in day.habit_schedules:
            if habit_schedule.time_spent:
                habit_schedule.time_spent = int(round(habit_schedule.time_spent.total_seconds() / 60))

        # Count the number of successful habit schedules for the day
        successful_schedules_count = HabitSchedule.objects.filter(
            day=day, completion_status="success"
        ).count()

        # Calculate the percentage
        total_schedules_count = HabitSchedule.objects.filter(day=day).count()
        percentage_success = (
            (successful_schedules_count / total_schedules_count) * 100 if total_schedules_count > 0 else 0
        )

        day.percentage_success = round(percentage_success, 2)

    previous_year, next_year, previous_week, next_week = calculate_weeks_and_years(
        current_week.week_number, current_week.year
    )

    return render(
        request,
        "habit_tracker/pages/week.html",
        context={
            "days": week_days,
            "week": {
                "previous_week": previous_week,
                "next_week": next_week,
                "current_week": current_week.week_number,
                "present_week": datetime.now().date().isocalendar()[1],
            },
            "previous_year": previous_year,
            "next_year": next_year,
            "current_year": year,
            "present_year": datetime.now().date().year,
        },
    )


@login_required
def create_habit(request):
    if request.method == "POST":
        # Accessing the selected habit ID
        habit_name = request.POST.get("habit_name", None)

        habit = Habit.objects.create(name=habit_name, user=request.user)

        form_days_of_week = request.POST.getlist("day_of_week")
        db_days_of_week = DayOfWeekChoice.objects.filter(day_of_week__in=form_days_of_week)

        start_date = request.POST.get("start_date", None)
        end_date = request.POST.get("end_date", None)

        if not end_date:
            end_date = None

        habit_recurrence = HabitRecurrence.objects.create(
            habit=habit, start_date=start_date, end_date=end_date
        )
        habit_recurrence.days_of_week.add(*db_days_of_week)
        habit_recurrence.save()

        create_schedules(habit, habit_recurrence, db_days_of_week)

        return HttpResponseRedirect(reverse("habit_tracker:habit_tracker"))
    else:
        habits = Habit.objects.all()

    return render(request, "habit_tracker/pages/create-habit.html", context={"habits": habits})


@login_required
def update_recurrence(request):
    if request.method == "POST":
        form_days_of_week = request.POST.getlist("day_of_week")
        start_date = request.POST.get("start_date", None)
        habit_to_update_id = request.POST.get("habit_to_update", None)

        if not all([form_days_of_week, start_date, habit_to_update_id]):
            return HttpResponseBadRequest("Invalid form data.")

        try:
            habit_to_update = Habit.objects.get(id=habit_to_update_id)
        except Habit.DoesNotExist:
            return HttpResponseBadRequest("Invalid habit id.")

        # Parse start_date to a datetime object
        start_date = timezone.datetime.strptime(start_date, "%Y-%m-%d").date()

        recurrence = HabitRecurrence.objects.filter(
            habit=habit_to_update,
        ).first()

        # Update days_of_week for the recurrence
        recurrence.days_of_week.set(DayOfWeekChoice.objects.filter(day_of_week__in=form_days_of_week))
        recurrence.start_date = start_date
        recurrence.save()

        # Delete schedules after the start_date
        schedules_to_delete = HabitSchedule.objects.filter(
            habit=habit_to_update,
            day__date__gte=start_date,
        )

        schedules_to_delete.delete()

        return redirect("habit_tracker:habit_tracker")

    else:
        habits = Habit.objects.all()
        return render(request, "habit_tracker/pages/update-recurrence.html", context={"habits": habits})


class MarkCompletedView(View):
    def post(self, request, *args, **kwargs):
        habit_schedule_id = request.POST.get("habit_schedule_id")

        habit_schedule = HabitSchedule.objects.get(id=habit_schedule_id)

        if habit_schedule:
            completion_status = request.POST.get("completion_status", None)
            description = request.POST.get("description", None)
            time_spent = request.POST.get("time_spent", None)

            habit_schedule.completion_status = completion_status
            habit_schedule.description = description

            # Convert time_spent to timedelta and update the habit_schedule
            if time_spent is not None and time_spent != "":
                time_spent_minutes = int(time_spent)
                habit_schedule.time_spent = timedelta(minutes=time_spent_minutes)

            habit_schedule.save()

        return redirect("habit_tracker:habit_tracker", week_number=kwargs["week"], year=kwargs["year"])

life-manager-app/apps/habit_tracker/templates/habit_tracker/pages/create-habit.html
{% extends 'global/base.html' %}

{% block title %}Create Habit | {% endblock title %}

{% block content %}

<div class="d-flex flex-column mt-5 align-items-center">
    <h1 class="text-center">
        Create Habit
    </h1>

    <form class="mt-5" method="post" action="{% url 'habit_tracker:create_habit' %}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="habitName" class="form-label">Habit Name</label>
            <input type="text" class="form-control" id="habitName" aria-describedby="habitName" name="habit_name">


            <label class="form-label">Days of The Week</label>
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="Sunday" name="day_of_week" value="Sunday" >
                <label class="form-check-label" for="Sunday">Sunday</label>
            </div>
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="Monday" name="day_of_week" value="Monday">
                <label class="form-check-label" for="Monday">Monday</label>
            </div>
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="Tuesday" name="day_of_week" value="Tuesday">
                <label class="form-check-label" for="Tuesday">Tuesday</label>
            </div>
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="Wednesday" name="day_of_week" value="Wednesday">
                <label class="form-check-label" for="Wednesday">Wednesday</label>
            </div>
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="Thursday" name="day_of_week" value="Thursday">
                <label class="form-check-label" for="Thursday">Thursday</label>
            </div>
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="Friday" name="day_of_week" value="Friday">
                <label class="form-check-label" for="Friday">Friday</label>
            </div>
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="Saturday" name="day_of_week" value="Saturday">
                <label class="form-check-label" for="Saturday">Saturday</label>
            </div>

            <label for="startDate" class="form-label">Start Date</label>
            <input type="text" class="form-control" id="startDate" aria-describedby="startDate" name="start_date">


            <label for="endDate" class="form-label">End Date</label>
            <input type="text" class="form-control" id="endDate" aria-describedby="endDate" name="end_date">


        </div>
        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
</div>


{% endblock content %}

life-manager-app/apps/habit_tracker/templates/habit_tracker/pages/update-recurrence.html
{% extends 'global/base.html' %}

{% block title %}Update Habit Recurrence | {% endblock title %}

{% block content %}

<div class="d-flex flex-column mt-5 align-items-center">
    <h1 class="text-center">
        Update Habit Recurrence
    </h1>

    <form class="mt-5" method="post" action="{% url 'habit_tracker:update_recurrence' %}">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Habits</label>
            <select class="form-select" name="habit_to_update" aria-label="Habits">
                {% for habit in habits %}
                <option value="{{ habit.id }}">{{ habit.name }}</option>
                {% endfor %}
            </select>


            <label class="form-label">Days of The Week</label>
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="Sunday" name="day_of_week" value="Sunday">
                <label class="form-check-label" for="Sunday">Sunday</label>
            </div>
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="Monday" name="day_of_week" value="Monday">
                <label class="form-check-label" for="Monday">Monday</label>
            </div>
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="Tuesday" name="day_of_week" value="Tuesday">
                <label class="form-check-label" for="Tuesday">Tuesday</label>
            </div>
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="Wednesday" name="day_of_week" value="Wednesday">
                <label class="form-check-label" for="Wednesday">Wednesday</label>
            </div>
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="Thursday" name="day_of_week" value="Thursday">
                <label class="form-check-label" for="Thursday">Thursday</label>
            </div>
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="Friday" name="day_of_week" value="Friday">
                <label class="form-check-label" for="Friday">Friday</label>
            </div>
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="Saturday" name="day_of_week" value="Saturday">
                <label class="form-check-label" for="Saturday">Saturday</label>
            </div>

            <label for="startDate" class="form-label">Date to Start the Update</label>
            <input type="text" class="form-control" id="startDate" aria-describedby="startDate" name="start_date">

        </div>
        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
</div>


{% endblock content %}

life-manager-app/apps/habit_tracker/templates/habit_tracker/pages/week.html
{% extends 'global/base.html' %}

{% block title %}Habit Tracker | {% endblock title %}

{% block content %}

<div class="container-fluid d-flex align-items-left border-top border-bottom p-3">
    <a href="{% url 'habit_tracker:habit_tracker' week.present_week present_year %}"
        class="text-center btn btn-primary me-1">
        Today
    </a>
    <a href="{% url 'habit_tracker:create_habit' %}"
        class="text-center btn btn-primary me-1">
        Create Habit
    </a>
    <a href="{% url 'habit_tracker:update_recurrence' %}"
        class="text-center btn btn-primary">
        Update Recurrence
    </a>
</div>


<div class="row h-100 mt-4">
    <div id="custom-narrow-col" class="col d-flex align-items-center justify-content-center p-0">
        <a href="{% url 'habit_tracker:habit_tracker' week.previous_week previous_year %}"
            class="w-100 h-100 d-flex align-items-center justify-content-center">
            <i class="bi bi-caret-left-fill fs-4 text-white"></i>
        </a>
    </div>

    {% for day in days %}
    <div id="separator" class="border-end col"></div>

    <div class="col">
        <div class="d-flex flex-column justify-content-center">
            <h3 class="text-center">{{ day.day_name }}</h3>
            <p class="text-center">{{ day.formated_date }}</p>
            <p class="badge {% if day.percentage_success > 90 %} bg-success {% else %} bg-danger {% endif %}">
                {{ day.percentage_success }}%</p>
        </div>

        <!-- Habits Section -->
        <div class="list-group">
            {% for habit_schedule in day.habit_schedules %}
            <div class="list-group-item list-group-item-action d-flex align-items-center border-bottom-0">
                <div class="d-flex flex-column">
                    <h6 class="mb-0">{{ habit_schedule.habit.name }}</h6>
                    {% if habit_schedule.habit.goal %}
                        <small id="goal">{{ habit_schedule.habit.goal }}</small>
                    {% endif %}
                </div>

                <div class="ms-auto">
                    <button type="button" class="btn" data-bs-toggle="modal"
                        data-bs-target="#modal{{ habit_schedule.id }}">
                        {% if habit_schedule.completion_status == 'success' %}
                        <i class="bi bi-x"></i>
                        {% else %}
                        <i class="bi bi-check"></i>
                        {% endif %}
                    </button>
                </div>
            </div>
            <div
                class="list-group-item-bottom-border border-5 {% if habit_schedule.completion_status == 'success' %} border-bottom border-success {% elif habit_schedule.completion_status == 'failed' %} border-bottom border-danger {% else %} border-bottom border-secondary {% endif %}">
            </div>
            {% endfor %}
        </div>
    </div>

    {% if day.day_name == "Saturday" %}
    <div id="separator" class="border-end col"></div>
    {% endif %}

    {% for habit_schedule in day.habit_schedules %}
    <!-- Modal -->
    <div class="modal fade" id="modal{{ habit_schedule.id }}" tabindex="-1" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Mark Completion of {{ habit_schedule.habit.name }}</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="post"
                        action="{% url 'habit_tracker:mark_completed' week.current_week current_year day.date %}">
                        {% csrf_token %}

                        <input type="text" class="form-control d-none" id="habit_schedule" name="habit_schedule_id" aria-describedby="habitScheduleId" value="{{ habit_schedule.id }}">

                        <div class="mb-3">
                            <label for="description" class="form-label">Description</label>
                            {% if habit_schedule.description != None %}
                                <textarea class="form-control" id="description" name="description">{{ habit_schedule.description }}</textarea>
                            {% else %}
                                <textarea class="form-control" id="description" name="description"></textarea>
                            {% endif %}

                        </div>


                        <div class="mb-3">
                            <label class="form-label">Completion Status</label>
                            <div class="form-check">
                                <input type="radio" class="form-check-input" id="success" name="completion_status"
                                    value="success" {% if habit_schedule.completion_status == "success" %} checked {% endif %}>
                                <label class="form-check-label" for="success">Success</label>
                            </div>
                            <div class="form-check">
                                <input type="radio" class="form-check-input" id="failed" name="completion_status"
                                    value="failed" {% if habit_schedule.completion_status == "failed" %} checked {% endif %}>
                                <label class="form-check-label" for="failed">Failed</label>
                            </div>
                            <div class="form-check">
                                <input type="radio" class="form-check-input" id="not_completed" name="completion_status"
                                    value="not_completed" {% if habit_schedule.completion_status == "not_completed" %} checked {% endif %}>
                                <label class="form-check-label" for="not_completed">Not Completed</label>
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="time_spent" class="form-label">Time Spent (in minutes)</label>
                            {% if habit_schedule.time_spent != 0 %}
                                <input type="number" class="form-control" id="time_spent" name="time_spent" min="0" value="{{ habit_schedule.time_spent }}">
                            {% else %}
                                <input type="number" class="form-control" id="time_spent" name="time_spent" min="0" value="0">
                            {% endif %}
                        </div>

                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>

            </div>
        </div>
    </div>
    {% endfor %}

    {% endfor %}

    <div id="custom-narrow-col" class="col d-flex align-items-center justify-content-center p-0">
        <a href="{% url 'habit_tracker:habit_tracker' week.next_week next_year %}"
            class="w-100 h-100 d-flex align-items-center justify-content-center">
            <i class="bi bi-caret-right-fill fs-4 text-white"></i>
        </a>
    </div>

</div>


{% endblock content %}